(in-package #:net.mfiano.lisp.algae.noise)

(u:define-constant +simplex-3d/skew-factor+ (/ 3d0))

(u:define-constant +simplex-3d/unskew-factor+ (/ 6d0))

(u:define-constant +simplex-3d/scale+ 32d0)

(u:defun-inline %simplex-3d (x y z)
  (declare (optimize speed)
           (f50 x y z))
  (flet ((get-simplex (x y z)
           (if (>= x y)
               (cond
                 ((>= y z) (values 1 0 0 1 1 0))
                 ((>= x z) (values 1 0 0 1 0 1))
                 (t (values 0 0 1 1 0 1)))
               (cond
                 ((< y z) (values 0 0 1 0 1 1))
                 ((< x z) (values 0 1 0 0 1 1))
                 (t (values 0 1 0 1 1 0)))))
         (noise (hash x y z)
           (let* ((s (- 0.6 (* x x) (* y y) (* z z)))
                  (h (logand hash 15))
                  (u (if (< h 8) x y))
                  (v (case h
                       ((0 1 2 3) y)
                       ((12 14) x)
                       (t z)))
                  (grad (+ (if (zerop (logand h 1)) u (- u))
                           (if (zerop (logand h 2)) v (- v)))))
             (if (plusp s)
                 (* (expt s 4) grad)
                 0d0))))
    (u:mvlet* ((s (* (+ x y z) +simplex-3d/skew-factor+))
               (i (floor (+ x s)))
               (j (floor (+ y s)))
               (k (floor (+ z s)))
               (tx (* (+ i j k) +simplex-3d/unskew-factor+))
               (x1 (- x (- i tx)))
               (y1 (- y (- j tx)))
               (z1 (- z (- k tx)))
               (i1 j1 k1 i2 j2 k2 (get-simplex x1 y1 z1))
               (x2 (+ (- x1 i1) +simplex-3d/unskew-factor+))
               (y2 (+ (- y1 j1) +simplex-3d/unskew-factor+))
               (z2 (+ (- z1 k1) +simplex-3d/unskew-factor+))
               (x3 (+ (- x1 i2) (* +simplex-3d/unskew-factor+ 2)))
               (y3 (+ (- y1 j2) (* +simplex-3d/unskew-factor+ 2)))
               (z3 (+ (- z1 k2) (* +simplex-3d/unskew-factor+ 2)))
               (x4 (+ (1- x1) (* +simplex-3d/unskew-factor+ 3)))
               (y4 (+ (1- y1) (* +simplex-3d/unskew-factor+ 3)))
               (z4 (+ (1- z1) (* +simplex-3d/unskew-factor+ 3)))
               (p +permutation+)
               (g1 (pget p i j k))
               (g2 (pget p (+ i i1) (+ j j1) (+ k k1)))
               (g3 (pget p (+ i i2)  (+ j j2) (+ k k2)))
               (g4 (pget p (1+ i) (1+ j) (1+ k)))
               (n1 (noise g1 x1 y1 z1))
               (n2 (noise g2 x2 y2 z2))
               (n3 (noise g3 x3 y3 z3))
               (n4 (noise g4 x4 y4 z4)))
      (float (* (+ n1 n2 n3 n4) +simplex-3d/scale+) 1f0))))

(defun simplex-3d (x y z)
  (declare (real x y z))
  (%simplex-3d (float x 1d0) (float y 1d0) (float z 1d0)))
